apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-data-connector
  name: truck-data-connector
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-data-connector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-data-connector
    spec:
      containers:
      - image: d2iqdemo/truck-data-connector:latest
        imagePullPolicy: Always
        name: truck-data-connector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: Kafka
          valueFrom:
            configMapKeyRef:
              name: dataservices
              key: Kafka
        - name: Topic
          value: 'trucks' 
        - name: Cassandra
          valueFrom:
            configMapKeyRef:
              name: dataservices
              key: Cassandra
      initContainers:
      - image: d2iqdemo/truck-cassandra-init:latest
        imagePullPolicy: Always
        name: cassandra-init
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: truck-data-connector-svc
spec:
  selector:
    app: truck-data-connector
  ports:
    - port: 8000
      targetPort: 8000
      name: data-connector
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: truck-data-connector-ingressroute
spec:
  routes:
    - match: PathPrefix(`/data-connector`)
      kind: Rule
      services:
        - name: truck-data-connector-svc
          port: data-connector
      middlewares:
        - name: data-connector-stripprefix
  tls:
    secretName: tls-data-connector
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: data-connector-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /data-connector
    forceSlash: true
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-data-connector
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

