---
apiVersion: v1
kind: Service
metadata:
  name: truck-data-api-svc
spec:
  type: ClusterIP
  selector:
    app: truck-data-api
  ports:
    - port: 8080
      targetPort: 8080
      name: data-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-data-api
  name: truck-data-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-data-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-data-api
    spec:
      containers:
      - image: d2iqdemo/truck-data-api:latest
        imagePullPolicy: Always
        name: truck-data-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CURRENT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: KAFKA
          valueFrom:
            configMapKeyRef:
              name: dataservices
              key: Kafka
      initContainers:
      - image: d2iqdemo/truck-kafka-init:latest
        imagePullPolicy: Always
        name: truck-kafka-init
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
status: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: truck-data-api-ingressroute
spec:
  routes:
    - match: PathPrefix(`/data-api`)
      kind: Rule
      services:
        - name: truck-data-api-svc
          port: data-api
      middlewares:
        - name: data-api-stripprefix
  tls:
    secretName: tls-data-api
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: data-api-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /data-api
    forceSlash: true
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-data-api
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
